### PR TITLE
Allow sharing link and copying its title

### PR DESCRIPTION
**Pull request by roundedrectangle**
Hello! I wanted to use your module in my application, but felt like it is missing lots of features. Here is what this PR adds:

- A button to share the link using Sailfish.Share module
- A button to copy the title, if available
- Change the button size logic because there are more buttons now

I'm also planning on creating a PR for previewing the link using Sailfish.WebView if this one gets approved

### CODE REVIEW

**Comment by roundedrectangle** [comment]
I thinked about this PR again and decided that having a dependency on Sailfish.Share and/or Sailfish.WebView would be bad for a module. Closing

**Comment by ichthyosaurus** [comment]
No wait, I really like what you did there! I just didn't have time yet to properly test and review it. In my opinion, the new dependencies are not an issue as they are both allowed in Harbour (https://docs.sailfishos.org/Develop/Apps/Harbour/Allowed_APIs/).

Maybe the internal preview using Sailfish.WebView is too much as it would force apps to require the Internet permission but other than that nothing problematic comes to mind.

**Comment by roundedrectangle** [comment]
Oh really? Alright then. As for the WebView, I think it could be implemented in one of these ways:

- An argument in the function (`LinkHandler.openOrCopyUrl`)
- Check the enabled SailJail permissions, maybe in the `.desktop` file
- Check if Sailfish.WebView module can be imported and Internet is accessible without checking the permissions. This method might require additional Internet requests for checking if it is available, which is not ideal.

**Comment by roundedrectangle** [comment]
Okay, I'll create a separate PR after this one gets accepted (if it will, of course).

**Comment by roundedrectangle** [comment]
Hello once again, i will log my webview research updates here if you don't mind :)

I found how to check internet connection in pure qml: with `nemo-qml-plugin-dbus` and connman's [D-Bus API](https://sailfishos.org/develop/docs/connman/service-api.html/). In short, we should call the `getServices` method on the `net.connman.Manager` interface and check if there are online interfaces. Here is a section of the [docs](https://sailfishos.org/develop/docs/connman/service-api.html/) about the state property:

> Properties	string State [readonly]
>
> The service state information.
>
> Valid states are "idle", "failure", "association",
> "configuration", "ready", "disconnect" and "online".
>
> The "ready" state signals a successfully
> connected device. "online" signals that an
> Internet connection is available and has been
> verified.
>
> See doc/overview-api.txt for more information about
> state transitions.

I already used connman's [GlobalProxy API](https://sailfishos.org/develop/docs/connman/globalproxy-api.html/) for proxy support in my app, so I have experience with this

**Pull request merged**
